# 팀원들의 예측 파일을 평균 내는 등과 같이 앙상블을 할 경우
- 팀원들에게 csv 파일 만들때 1에 대한 확률로 예측할 것을 요구해야 함

In [1]:
import pandas as pd
import numpy as np

DATA_PATH = "C:/Users/user/Desktop/데이터분석/05 Project_Final/Data/"

train_tr = pd.read_csv(f"{DATA_PATH}store_train_transactions.csv") # 학습용 구매기록 데이터
train_target = pd.read_csv(f"{DATA_PATH}store_train.csv") # 학습용 정답 데이터
test_tr = pd.read_csv(f"{DATA_PATH}store_test_transactions.csv") # 테스트용 구매기록 데이터
submit = pd.read_csv(f"{DATA_PATH}store_submission.csv") # 제출 양식 데이터

train_tr.shape , train_target.shape , test_tr.shape , submit.shape

((523105, 7), (14940, 2), (441196, 7), (12225, 2))

In [3]:
DATA_PATH = "C:/Users/user/Desktop/데이터분석/05 Project_Final/Submit_csv/"

# 01

In [ ]:
proba_1 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_O_proba.csv")  # 현설_ 군집_스케일링O (0.723658)
proba_2 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_X_proba.csv")  # 현설_ 군집_스케일링X (0.723658)
proba_3 = pd.read_csv(f"{DATA_PATH}6조_v3.0_proba.csv")                 # 공통피처 v3.0 (0.725006)

In [4]:
pred = np.mean(
        [
            proba_1["target"].to_numpy(),
            proba_2["target"].to_numpy(),
            proba_3["target"].to_numpy()
        ],axis=0)
pred.shape

(12225,)

In [5]:
pred = (pred >= 0.5).astype(int)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
submit = proba_1[["ID"]]
submit["target"] = pred
submit

ID  target
0          test_0       0
1          test_1       0
2          test_2       0
3          test_3       1
4          test_4       1
...           ...     ...
12220  test_12220       1
12221  test_12221       0
12222  test_12222       0
12223  test_12223       0
12224  test_12224       0

[12225 rows x 2 columns]

In [7]:
submit.to_csv(f"{DATA_PATH}ensemble_01.csv",index=False)

# 02

In [18]:
import pandas as pd
import numpy as np

proba_1 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_O_proba.csv")  # 현설_ 군집_스케일링O (0.723658)
proba_2 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_X_proba.csv")  # 현설_ 군집_스케일링X (0.723658)
proba_3 = pd.read_csv(f"{DATA_PATH}6조_v3.0_proba.csv")                 # 공통피처 v3.0 (0.725006)
proba_4 = pd.read_csv(f"{DATA_PATH}XGB_fs_proba_1108.csv")              # 서진_XGB (0.722212)
proba_5 = pd.read_csv(f"{DATA_PATH}LGBM_fs_logi_proba_1108.csv")        # 서진_LGBM_logi (0.717365)
proba_6 = pd.read_csv(f"{DATA_PATH}LGBM_fs_xgb_proba_1108.csv")         # 서진_LGBM_xgb (0.719888)

In [19]:
pred = np.mean(
        [
            proba_1["target"].to_numpy(),
            proba_2["target"].to_numpy(),
            proba_3["target"].to_numpy(),
            proba_4["target"].to_numpy(),
            proba_5["target"].to_numpy(),
            proba_6["target"].to_numpy(),
        ],axis=0)
pred.shape

(12225,)

In [16]:
pred = (pred >= 0.5).astype(int)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
pred.mean()

0.3398773006134969

In [11]:
submit = proba_1[["ID"]]
submit["target"] = pred
submit

ID  target
0          test_0       0
1          test_1       0
2          test_2       0
3          test_3       1
4          test_4       1
...           ...     ...
12220  test_12220       1
12221  test_12221       0
12222  test_12222       0
12223  test_12223       0
12224  test_12224       0

[12225 rows x 2 columns]

In [12]:
submit.to_csv(f"{DATA_PATH}ensemble_02.csv",index=False)

- 임계값 조정

In [20]:
pred = (pred >= 0.4).astype(int)
submit = proba_1[["ID"]]
submit["target"] = pred
submit.to_csv(f"{DATA_PATH}ensemble_02_1.csv",index=False)

In [22]:
pred.mean()

0.4383640081799591

# 03

In [29]:
import pandas as pd
import numpy as np

proba_1 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_O_proba.csv")  # 현설_ 군집_스케일링O (0.723658)
proba_2 = pd.read_csv(f"{DATA_PATH}v3.2_XGB_cluster_proba.csv")         # 현설_v3.2_optuna_XGB (0.724409)
proba_3 = pd.read_csv(f"{DATA_PATH}6조_v3.0_proba.csv")                 # 공통피처 v3.0 (0.725006)
proba_4 = pd.read_csv(f"{DATA_PATH}v3.0_XGB_cluster_proba.csv")         # 현설_v3.2_optuna_XGB (0.725341)

In [30]:
pred = np.mean(
        [
            proba_1["target"].to_numpy(),
            proba_2["target"].to_numpy(),
            proba_3["target"].to_numpy(),
            proba_4["target"].to_numpy(),

        ],axis=0)
pred.shape

(12225,)

In [17]:
pred = (pred >= 0.5).astype(int)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
submit["target"] = pred
submit

ID  target
0          test_0       0
1          test_1       0
2          test_2       0
3          test_3       1
4          test_4       1
...           ...     ...
12220  test_12220       1
12221  test_12221       0
12222  test_12222       0
12223  test_12223       0
12224  test_12224       0

[12225 rows x 2 columns]

In [19]:
submit.to_csv(f"{DATA_PATH}ensemble_03.csv",index=False)

- 임계값 조정

In [31]:
pred = (pred >= 0.41).astype(int)
submit["target"] = pred
submit.to_csv(f"{DATA_PATH}ensemble_03_0.41.csv",index=False)

# 04

In [21]:
import pandas as pd
import numpy as np

proba_1 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_O_proba.csv")  # 현설_ 군집_스케일링O (0.723658)
proba_2 = pd.read_csv(f"{DATA_PATH}6조_v3.2_1108_cluster_X_proba.csv")  # 현설_ 군집_스케일링X (0.723658)
proba_3 = pd.read_csv(f"{DATA_PATH}6조_v3.0_proba.csv")                 # 공통피처 v3.0 (0.725006)
proba_4 = pd.read_csv(f"{DATA_PATH}v3.2_XGB_cluster_proba.csv")         # 현설_v3.2_optuna_XGB (0.724409)
proba_5 = pd.read_csv(f"{DATA_PATH}v3.0_XGB_cluster_proba.csv")         # 현설_v3.2_optuna_XGB (0.725341)
proba_6 = pd.read_csv(f"{DATA_PATH}XGB_fs_proba_1108.csv")              # 서진_XGB (0.722212)
proba_7 = pd.read_csv(f"{DATA_PATH}LGBM_fs_logi_proba_1108.csv")        # 서진_LGBM_logi (0.717365)
proba_8 = pd.read_csv(f"{DATA_PATH}LGBM_fs_xgb_proba_1108.csv")         # 서진_LGBM_xgb (0.719888)


In [26]:
pred = np.mean(
        [
            proba_1["target"].to_numpy(),
            proba_2["target"].to_numpy(),
            proba_3["target"].to_numpy(),
            proba_4["target"].to_numpy(),
            proba_5["target"].to_numpy(),
            proba_6["target"].to_numpy(),
            proba_7["target"].to_numpy(),
            proba_8["target"].to_numpy(),

        ],axis=0)
pred.shape

(12225,)

In [23]:
pred = (pred >= 0.5).astype(int)
pred

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
submit["target"] = pred
submit

ID  target
0          test_0       0
1          test_1       0
2          test_2       0
3          test_3       1
4          test_4       1
...           ...     ...
12220  test_12220       1
12221  test_12221       0
12222  test_12222       0
12223  test_12223       0
12224  test_12224       0

[12225 rows x 2 columns]

In [25]:
submit.to_csv(f"{DATA_PATH}ensemble_04.csv",index=False)

- 임계값 조정

In [28]:
pred = (pred >= 0.41).astype(int)
submit["target"] = pred
submit.to_csv(f"{DATA_PATH}ensemble_04_0.41.csv",index=False)